spring:
    application:
        name: stats-api
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    profiles:
        active: local
server:
    port: 8080
    servlet:
        context-path: /
logging:
    level:
        ROOT: INFO
stats-api:
    service:
        expiry-interval: 60s
        expiry-clean-up-interval: 90s
springdoc:
    swagger-ui:
        api:
            group-name: Real-time Statistics API
            controller-package: net.sattler22.stats.controller
        info:
            title: Spring Boot Real-time Statistics REST API
            description: Collects real-time statistics for transactions that took place in the last ${stats-api.service.expiry-interval} seconds
            license: Mozilla Public License 2.0
            licenseUrl: https://mozilla.org/MPL/2.0
            version: "@project.version@"
        operations-sorter: alpha
...