spring:
    application:
        name: stats-api
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    profiles:
        active: local
logging:
    level:
        ROOT: INFO
server:
    servlet:
        context-path: /
stats-api:
    service:
        expiry-interval-secs: 60
        expiry-clean-up-interval-secs: 90
swagger-endpoint:
    title: Spring Boot Real-time Statistics REST API
    description: Collects real-time statistics for transactions that took place in the last ${stats-api.service.expiry-interval-secs} seconds
    license: Mozilla Public License 2.0
    licenseUrl: http://mozilla.org/MPL/2.0
    version: "@project.version@"
    host: localhost:8080
...